Add command to trim streams
handcraftedinthealps/RedisTransportBundle pull request #17
Opened 2019-07-29 11:11 UTC by wachterjohannes

2019-07-29 13:52 UTC, alexander-schranz requested changes

2019-07-29 13:52 UTC, alexander-schranz commented on Command/TrimRedisStreamCommand.php
> +
add also:

```
if ($errorMessage = $redis->getLastError()) {
    throw new \RuntimeException($errorMessage);
}
```

2019-07-29 13:53 UTC, alexander-schranz commented on Command/TrimRedisStreamCommand.php
> +        $x = $redis->xTrim($stream, (int) $maxLength, true);
xtrim need to be lowercase else prophecy will fail because its case sensitive

2019-07-29 14:01 UTC, alexander-schranz commented
any way to provide a test for this command?

2019-07-29 14:34 UTC, wachterjohannes commented
@alexander-schranz we would have to create a functional testcase - is there already a setup for this?

2019-07-29 15:36 UTC, alexander-schranz commented on Command/TrimRedisStreamCommand.php
> +     * @var \Redis
```
@var \Redis|null
```

2019-07-30 07:54 UTC, alexander-schranz approved these changes

2019-07-30 07:54 UTC, merged